SERVER_WORKING_DIR: "/var/www/sunspot"
GTFS_ZIP_FILE_STRING: "/var/www/sunspot/gtfs.zip"
GTFS_ZIP_FILE_URL: "http://suntran.com/gtfs/SuntranGTFS.zip"
HTTP_HEADER_LAST_MODIFIED_FORMAT: "ddd, D MMM YYYY HH:mm:ss"
# CONFIG_FILE_PATH: "/var/www/sunspot/config.yaml"
#ZERO_VERSION_UUID = uuid.UUID('00000200-0000-0000-0000-000000000000')
REMOTE_ENDPOINT: "http://mgrandi.no-ip.org:81/sunspot"
CHOWN_OWNER: "mark"
CHOWN_GROUP: "www-data"
DB_FOLDER: "/var/www/sunspot/dbs/"
DB_PATCHES_FOLDER: "/var/www/sunspot/dbs_patches/"
CONFIG_DB_PATH: "/var/www/sunspot/configdb"

SERVERDATABASE_LOGGING_OUTPUT_TO_CONSOLE: false # if false then we use the rotating file handler

# ignored if we OUTPUT_TO_CONSOLE is true
SERVERDATABASE_LOGGING_OUTPUT_NAME: "/var/www/sunspot/logs/LeveldbServer.log"
SERVERDATABASE_LOGGING_MAXBYTES: 102400
SERVERDATABASE_LOGGING_NUMBACKUPS: 5
SERVERDATABASE_LOGGING_LEVEL: "DEBUG"